/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShowId = IDL.Nat;
export const ShowType = IDL.Variant({
  'movie' : IDL.Null,
  'series' : IDL.Null,
});
export const Show = IDL.Record({
  'id' : ShowId,
  'title' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'posterUrl' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'showType' : ShowType,
  'isNew' : IDL.Bool,
});
export const CategoryId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
  'getFeaturedShow' : IDL.Func([], [IDL.Opt(Show)], ['query']),
  'getShowsByCategory' : IDL.Func([CategoryId], [IDL.Vec(Show)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShowId = IDL.Nat;
  const ShowType = IDL.Variant({ 'movie' : IDL.Null, 'series' : IDL.Null });
  const Show = IDL.Record({
    'id' : ShowId,
    'title' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'posterUrl' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'showType' : ShowType,
    'isNew' : IDL.Bool,
  });
  const CategoryId = IDL.Nat;
  
  return IDL.Service({
    'getAllShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
    'getFeaturedShow' : IDL.Func([], [IDL.Opt(Show)], ['query']),
    'getShowsByCategory' : IDL.Func([CategoryId], [IDL.Vec(Show)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };